// Getters

export const GET_FILTERED_HEROES = "GET_FILTERED_HEROES";
export const GET_SELECTED_TEAM_MEMBER = "GET_SELECTED_TEAM_MEMBER";

// Mutations

export const ADD_TEAM_MEMBER = "ADD_TEAM_MEMBER";
export const REMOVE_TEAM_MEMBER = "REMOVE_TEAM_MEMBER";
export const SELECT_TEAM_MEMBER = "SELECT_TEAM_MEMBER";
export const SET_HERO_FILTER = "SET_HERO_FILTER";
export const SET_HEROES = "SET_HEROES";

// Actions

export const FETCH_HEROES = "FETCH_HEROES";
